theme: minima  #jekyll-theme-cayman

title: Qibin Hou's Homepage

# User settings
author: Qibin Hou
username: Qibin Hou
user_description: I'm a research fellow at NUS
user_title: Research Fellow
email: andrewhoux@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  I am currently a research fellow at NUS working with Prof. Jiashi Feng.


show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    #twitter: xxxx
    github:  Andrew-Qibin

plugins:
 - jekyll-feed
 - jekyll-seo-tag
