theme: minima  #jekyll-theme-cayman

title: Qibin Hou's Homepage

# User settings
author: Qibin Hou
username: Qibin Hou
email: andrewhoux@gmail.com
# username: Qibin Hou
user_description: I'm a research fellow at NUS
user_title: Research Fellow

description: > # this means to ignore newlines until "show_excerpts:"
  I am currently a research fellow at NUS working with Prof. Jiashi Feng.


show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    #twitter: xxxx
    github:  Andrew-Qibin

plugins:
# - jekyll-sitemap
# - jekyll-mentions
# - jekyll-paginate
- jekyll-seo-tag
# - jekyll-redirect-from
# - jekyll-default-layout
- jekyll-feed
# - jekyll-commonmark
# - jekyll-include-cache
# - jemoji
