theme: minima  #jekyll-theme-cayman

title: Qibin Hou's Homepage

# User settings
username: Qibin Hou
user_description: I'm a research fellow at NUS
user_title: Research Fellow
email: andrewhoux@gmail.com

show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    #twitter: xxxx
    github:  Andrew-Qibin
